developmentseed/eoapi-cdk

- .github/workflows/tox.yaml
- .gitignore
- lib/ingestor-api/runtime/dev_requirements.txt
- lib/ingestor-api/runtime/requirements.txt
- lib/ingestor-api/runtime/src/config.py
- lib/ingestor-api/runtime/src/dependencies.py
- lib/ingestor-api/runtime/src/ingestor.py
- lib/ingestor-api/runtime/src/validators.py
- lib/ingestor-api/runtime/tests/conftest.py
- lib/ingestor-api/runtime/tests/test_registration.py
- lib/stac-api/runtime/src/app.py
- lib/stac-api/runtime/src/config.py
- tox.ini
This will likely be unnecessary once we extract the `stac-ingestor` Python lib to a separate module.
> Add python linting and test runner and corresponding Github action.

- lib/ingestor-api/runtime/src/collection.py
- lib/ingestor-api/runtime/src/ingestor.py
- lib/ingestor-api/runtime/src/utils.py
The migration of collection creation code from `veda-stac-ingestor` introduced several regressions and revealed some code fixes that were not migrated in previous PRs.
> Fix ingestor regressions introduced by developmentseed/cdk-pgstac/pull/18.

- .github/workflows/conventional-pr.yaml
Suggesting that we add https://github.com/marketplace/actions/conventional-pull-request. It has support for both validating PR Titles and commit messages.
Also reviewed:
* https://github.com/Namchee/conventional-pr - Probably more flexible and better community support, but I got overwhelmed will all the configuration
* https://github.com/marketplace/actions/conventional-pr-title - Only focused on titles, doesn't seem to address situations where commits get their message from the only commit in single-commit PRs.
> ci: add conventional commit pr check

- lib/ingestor-api/runtime/src/collection.py
- lib/ingestor-api/runtime/src/ingestor.py
- lib/ingestor-api/runtime/src/loader.py
- lib/ingestor-api/runtime/src/schemas.py
- lib/ingestor-api/runtime/src/utils.py
- lib/ingestor-api/runtime/tests/conftest.py
- lib/ingestor-api/runtime/tests/test_ingestor.py
- lib/ingestor-api/runtime/tests/test_registration.py
- lib/ingestor-api/runtime/tests/test_utils.py
This PR addresses the issue raised in https://github.com/NASA-IMPACT/veda-data-pipelines/issues/313.  The PR updates the ingestor code to serialize the STAC `item` property of the `ingestion` as a string prior to storing it in DynamoDB.  Additionally, it updates the code used to deserialize `ingestions` queried from the DynamoDB table and load them into `pgstac` and adds unit test coverage for some of the `ingestor` code paths (which previously had no coverage).
> fix(ingestor-api)!: store STAC item as string in DynamoDB

- lib/bootstrapper/runtime/handler.py
- lib/ingestor-api/runtime/src/loader.py
- lib/ingestor-api/runtime/src/utils.py
This PR addresses the issue raised in https://github.com/developmentseed/cdk-pgstac/issues/28. 
- removed the [VEDA schema and functions ingested here](https://github.com/developmentseed/cdk-pgstac/blob/4ef537c7ef5f3f7b8fd9b2cccd5e49633dd3aa3e/lib/bootstrapper/runtime/handler.py#L304), create_dashboard_schema, create_update_default_summaries_function, create_update_all_default_summaries_function.
- removed the usage of `update_default_summaries`, where we were updating the collection summary while inserting new items.
> refactor: remove VEDA logic

- lib/bootstrapper/index.ts
- lib/ingestor-api/runtime/src/collection.py
- lib/ingestor-api/runtime/tests/conftest.py
- lib/ingestor-api/runtime/tests/test_collection.py
> fix(bootstraper): fix version inconsistencies and #19 regressions

- lib/ingestor-api/index.ts
* added a new public read only handler_role property to the StacIngestor construct. As a consequence, I had to move the handler_role creation to the constructor.
* the role name is now automatically generated by AWS. We were manually defining it before so that users could import the role with its name (e.g to modify the data access role policy), but because we're now directly using the role object (i.e an `iam.Role` object) from the property, the name does not matter. Since manually defining a role name is restrictive (see the documentation of the parameter on the API reference), I think it's better to let AWS choose it. 
BREAKING CHANGE: the role name is automatically generated by AWS and thus users can not use the name that was specified before, but should directly interact with the new …
> feat(ingestor-api): expose ingestor handler role

- lib/bastion-host/index.ts
There was a typo 54322
But also the SSM example above fowards to 9999
This PR makes it consistent that 9999 is used as a localforward so it's clear what port is which.
> chore(docs): port consistency for Bastion host

- lib/bootstrapper/runtime/Dockerfile
- lib/bootstrapper/runtime/handler.py
Addresses https://github.com/developmentseed/cdk-pgstac/issues/44 by using httpx instead of requests in bootstrapper.
I tested this with cdk-pgstac deployment I am using for EODC (see https://github.com/developmentseed/tile-benchmarking/tree/feat/deploy-pgstac) where I made these changes in the installed node_module for cdk-pgstac and deployed.
> fix(bootstrapper): bootstrapper should use httpx

- lib/titiler-pgstac-api/index.ts
- lib/titiler-pgstac-api/runtime/Dockerfile
- package-lock.json
- package.json
minor fix 
Deployment in a github runner using the `ubuntu-latest` (with docker engine `20.10.24+azure-1`) was failing, with an error thrown [at this line in the process of building the `titiler-pgstac-api` docker image](https://github.com/developmentseed/cdk-pgstac/blob/5dcdd4468a477379b016f3fcf60ee0ec6d542e19/lib/titiler-pgstac-api/runtime/Dockerfile#L18) -- noting that local builds were running fine with docker engine `20.10.24` :
```
Step 12/13 : COPY runtime/src/*.py /asset
When using COPY with more than one source file, the destination must be a directory and end with a /
/home/runner/work/maap-cdk-pgstac/maap-cdk-pgstac/node_modules/aws-cdk-lib/core/lib/private/asset-staging.js:2
`).map((line,idx)=>`${idx===0?firstLine:padding}${line}`)};const reason=proc.signal!=null?`signal …
```
> fix(titiler-pgstac-api): fix destination path in titiler pgstac Dockerfile COPY command

- lib/ingestor-api/index.ts
The Cloud Formation export name of the ingestor api `api gateway endpoint` was "ingestor-api-{stage}". In the case of multiple deployments of these constructs in the same AWS account, stage and region, which can happen for experimental reasons, this creates problems (For each AWS account, an export name must be unique within a region https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html).
This PR adds the name of the stack as a prefix of the export name, like it's done for (most?) all the other exports in this library.
> fix(ingestor-api): add stack name to ingestor-api apigateway export name

- lib/stac-api/runtime/src/handler.py
- lib/titiler-pgstac-api/runtime/requirements.txt
- lib/titiler-pgstac-api/runtime/src/handler.py
This PR does:
- update titiler-pgstac version
- make sure to run the lifespan (https://github.com/stac-utils/stac-fastapi/issues/493)
> feat!: update titiler version and `fix` lifespan

- lib/ingestor-api/index.ts
- lib/stac-api/index.ts
- lib/titiler-pgstac-api/index.ts
- lib/titiler-pgstac-api/runtime/src/handler.py
- adds the ability for wrappers to pass custom domain names to apigateway constructs
- fixes a titiler-pgstac application bug introduced in https://github.com/developmentseed/eoapi-cdk/pull/61
example implementation: https://github.com/MAAP-Project/maap-eoapi/pull/15
> feat: custom domain names for apis

- lib/ingestor-api/runtime/src/handler.py
Closes https://github.com/developmentseed/eoapi-cdk/issues/79.
Not 100% sure what the mechanism is 🤷 but it works. Got the inspiration from : https://github.com/tiangolo/fastapi/issues/2872#issuecomment-1442736022
> fix(ingestor-api-handler): fix docs endpoint

- lib/database/bootstrapper_runtime/handler.py
New take at https://github.com/developmentseed/eoapi-cdk/pull/80, fixes misleading error message.
> fix(bootstrapper): fix httpx response

- lib/stac-browser/index.ts
The radiant earth STAC browser is configurable with a `config.js` placed at the root of the folder where the app is built. In this PR, I add an option for the user to provide the path to a local file that will replace the default `config.js` in the cloned STAC browser radiant earth repo https://github.com/radiantearth/stac-browser/blob/main/config.js. 
This allows for a flexible customization that limits maintenance work on our side. 
Clients may want, for example, to link that browser to their own tiler rather than the radiant earth tiler.
> feat(stac-browser): configurable config file in stac browser deployment

- .github/pull_request_template.md
- .github/workflows/deploy.yaml
In a [previous PR](https://github.com/developmentseed/eoapi-cdk/pull/69), I added a [workflow that was meant to run before any release](https://github.com/developmentseed/eoapi-cdk/issues/13) and which purpose is to use the constructs in a simple real-world deployment that we immediately destroy, before actually doing a release, to do a basic sanity check. 
The system doesn't work. As basic as it may sound, it's actually **_not_** easy to set that up. 
I recap. We have a long and costly job (deployment) that we want to run _only_ if a release is _about_ to happen. I contemplated two options to implement this : 
1. Add two steps before the `Maybe Release` step (that does the release) : `Check if release is going to happen`, which would produce a boolean output variable called …
> chore: make deployment workflow manual and add a reminder in pr template

- .github/workflows/conventional-pr.yaml
- lib/titiler-pgstac-api/runtime/Dockerfile
`numexpr>=2.10.1` requires `g++` when installing. See https://github.com/pydata/numexpr/issues/493 for an explanation.
Resolves #107
> fix: install compilation dependency for numexpr

- lib/database/index.ts
The `effectiveCacheSize` and `tempBuffers` parameters need to be described in number of 8kb blocks like `sharedBuffers`.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.Parameters.html
Successful deployment workflow run: https://github.com/developmentseed/eoapi-cdk/actions/runs/12241535813
> fix: update units for effectiveCacheSize and tempBuffers

- lib/database/bootstrapper_runtime/handler.py
Adding `pgstac` to the `search_path` for the eoapi database user makes it possible to use `pgbouncer` as a connection pooler for applications that connect to the pgstac database. Without setting this for the user it is impossible to use `pgbouncer` because it does not allow a client to specify options like `search_path` or `application_name` with the connection string.
successful deployment action: https://github.com/developmentseed/eoapi-cdk/actions/runs/12189254944/job/34004022350
> feat: set search_path to include pgstac for eoapi user

- .github/workflows/distribute.yaml
There is a bug in `twine` that causes this error: https://github.com/developmentseed/eoapi-cdk/actions/runs/12952156141/job/36130167690
see https://github.com/pypa/twine/issues/1216 for details
> fix: install packaging>=24.2 with twine

- .github/workflows/build.yaml
- integration_tests/cdk/app.py
- lib/database/PgBouncer.ts
- lib/database/index.ts
https://github.com/developmentseed/eoapi-cdk/actions/runs/13120415931/job/36604792924
Without adding adding this dependency it can be possible to for downstream constructs to try using the new secret before it has been updated!
> fix: ensure dependency secret update function completes

- lib/database/bootstrapper_runtime/Dockerfile
- lib/database/index.ts
enable configuration of pypgstac version in custom ressource properties
> feat: configure pgstac version in custom properties

- integration_tests/cdk/app.py
- lib/database/index.ts
- lib/ingestor-api/runtime/requirements.txt
fix: ensure db bootstrapper runs on each deploy
fix: advertise secretBootstrapper so other resources can use it as a dependency
This ensures that the bootstrapper `CustomResource` will run on every deploy, which will ensure that any changes to the bootstrap process get executed rather than just updating the Lambda and not invoking it. resolves #113.
I also added the `secretBootstrapper` attribute so other constructs can add it as a dependency (resolves #123)
> fix: ensure db bootstrapper runs on each deploy

- lib/ingestor-api/runtime/requirements.txt
- lib/ingestor-api/runtime/src/config.py
- lib/ingestor-api/runtime/src/schemas.py
- lib/ingestor-api/runtime/tests/conftest.py
- lib/ingestor-api/runtime/tests/test_registration.py
- tox.ini
The ingestor API has several out-of-date dependencies that are holding things back - this brings the ingestor runtime up to pydantic >= 2 and stac-pydantic >= 3
Resolves #119
> chore: update ingestor-api runtime dependencies

- lib/ingestor-api/runtime/src/config.py
- lib/ingestor-api/runtime/tests/conftest.py
- lib/ingestor-api/runtime/tests/test_validators.py
[successful deployment run](https://github.com/developmentseed/eoapi-cdk/actions/runs/13595654266/job/38011854616)
This updates the config to convert the urls to strings after validating the url with `AnyHttpUrl`.
Resolves #126
> fix: update types for url config parameters to be compatible with str

- lib/ingestor-api/runtime/src/collection.py
- lib/ingestor-api/runtime/src/utils.py
- lib/ingestor-api/runtime/tests/test_collection.py
- lib/ingestor-api/runtime/tests/test_utils.py
resolves #130
We did not have coverage for the case where a collection object is not JSON serializable. This fixes a bug with the pydantic>=2 upgrade and adds a test.
> fix: use model_dump(mode="json") for serializing STAC objects

- integration_tests/cdk/app.py
- lib/stac-api/index.ts
The transaction extension is not something we want to enable without an auth layer! This adds a field to the `PgStacApiLambdaProps` for providing a list of enabled extensions. It defaults to all of the extensions supported by stac-fastapi-pgstac except for the transaction and bulk transactions extensions.
Resolves #134
> fix: disable transaction extensions by default

- integration_tests/cdk/app.py
- lib/database/index.ts
- lib/ingestor-api/index.ts
- lib/ingestor-api/runtime/Dockerfile
- lib/ingestor-api/runtime/requirements.txt
- lib/ingestor-api/runtime/src/config.py
- lib/utils/index.ts
It is important for the ingestor API and the database to have the same version of pgstac/pypgstac. This moves the pypgstac version out of a hard-coded value in requirements.txt and into a configurable argument that is easier to keep in sync with the database.
I also added an ingestor deployment to the test deployment CDK app, which should pave the way for #117
> fix: refactor to keep database pgstac and ingestor pypgstac in sync

- package-lock.json
- package.json
> [!NOTE]
> Successful build: https://github.com/developmentseed/eoapi-cdk/actions/runs/14480817992/job/40617191146
I am trying to use `eoapi-cdk` on a project but find am unable to upgrade CDK beyond `2.130.0`:
```
▶ uv sync
× No solution found when resolving dependencies:
╰─▶ Because only eoapi-cdk<=8.0.2 is available and eoapi-cdk==8.0.2 depends on aws-cdk-lib==2.130.0, we can conclude that eoapi-cdk>=8.0.2 depends on
aws-cdk-lib==2.130.0.
And because my-project-aws depends on aws-cdk-lib>=2.189.0, we can conclude that -project-aws and eoapi-cdk>=8.0.2 are incompatible.
And because -project-aws depends on eoapi-cdk>=8.0.2 and your workspace requires -project-aws, we can conclude that your
workspace's requirements are unsatisfiable.
```
I would prefer to use the latest version of CDK …
> refactor: permit usage of higher CDK versions

- lib/tipg-api/runtime/src/handler.py
- lib/titiler-pgstac-api/runtime/src/handler.py
resolves #143
https://github.com/developmentseed/eoapi-cdk/actions/runs/14491012794/job/40647272705
I missed the tipg API update when updating handlers for the latest versions. This solves it and updates the titiler-pgstac handler to avoid setting postgres variables via `os.environ`.
> fix: update tipg startup for 1.0

- lib/stac-api/index.ts
- lib/tipg-api/index.ts
- lib/titiler-pgstac-api/index.ts
- package-lock.json
- package.json
**Build:** https://github.com/developmentseed/eoapi-cdk/actions/runs/14538121447
- Upgraded `aws-cdk-lib` to version `^2.190.0` in both `package.json` and `package-lock.json`.
- Removed deprecated `@aws-cdk/aws-apigatewayv2-alpha` and `@aws-cdk/aws-apigatewayv2-integrations-alpha` dependencies.
- Refactored API integration code to use the new `aws_apigatewayv2` and `aws_apigatewayv2_integrations` modules.
- Updated domain name handling in API constructs to align with new imports.
> chore: remove deprecated CDK packages from dependencies

- integration_tests/cdk/app.py
- lib/database/PgBouncer.ts
- lib/database/index.ts
This makes it possible for users to control more about the pgbouncer ec2 instance
> feat: add pgbouncerInstanceProps parameter to PgstacDatabase

- lib/database/PgBouncer.ts
- lib/database/pgbouncer-setup.sh
I also manually deployed a stack and verified that the pgbouncer service is working correctly after this change.
This helps reduce security vulnerabilities for the pgbouncer EC2 instance by upgrading to Ubuntu 24.04 and running `apt-get update` and `apt-get upgrade` to ensure that the latest packages are installed when the instance boots up.
> fix: upgrade pgbouncer ami to ubuntu 24.04

- lib/stac-item-loader/index.ts
- lib/stac-item-loader/runtime/src/stac_item_loader/handler.py
- lib/stac-item-loader/runtime/tests/test_item_load_handler.py
Enable a boilerplate collection record to be uploaded when an item's collection is not yet present in the database.
> fix: add option to create collection if missing

- lib/lambda-api-gateway-private/index.ts
Introduces a new construct, PrivateLambdaApiGateway, which allows the creation of a private REST API Gateway integrated with a Lambda function within a specified VPC. This includes options for VPC endpoint creation and customizable deployment settings.
> feat: add PrivateLambdaApiGateway construct for VPC-integrated API Gateway

- lib/index.ts
- lib/stac-auth-proxy/index.ts
- lib/stac-auth-proxy/runtime/Dockerfile
- lib/stac-auth-proxy/runtime/requirements.txt
- lib/stac-auth-proxy/runtime/src/handler.py
- package.json
currently available at https://pypi.org/project/eoapi-cdk/9.2.0rc3/
closes #170
> feat: add stac-auth-proxy construct

- lib/titiler-pgstac-api/runtime/Dockerfile
This was one of the main gotchas for the Python 3.12 runtime upgrade but I forgot about it :disappointed: 
From https://github.com/developmentseed/titiler/discussions/1108:
> I think it is a brittle solution but it might work for you too. The problem is that the execution environment is subtly different from the build environment as @vincentsarago suggested earlier. In this case the build environment (Lambda Python 3.12 image) has libexpat.so.1 available in the LD_LIBRARY_PATH which includes /usr/lib64 but the execution environment does not. The contents of the /asset directory which get zipped up to create the code package for the Lambda gets added to LD_LIBRARY_PATH so I think that's why it works. I hope that helps!
resolves #181
> fix: include libexpat.so.1 in the titiler code package
